### ISSUE TITLE
Question: Confused on how to support per-method security permissions

### ISSUE THREAD

**Issue by memelet** [kogosoftwarellc/express-openapi-security#2]
We use JWT (obtained via OAUTH2) to define a set of permissions. eg,
```
jwt: {
   perms: ['device:read', 'plan:edit']
   ...
}
```

So I would want to define something like
```
module.exports.get.apiDoc = {
  description: 'Get Device.',
  ...
  security: { permissions: ['device:read'] } 
}
```

Where my custom handler would get the array of required permissions and the jwt token.

Is this possible? I don't see anything like this here or in express-openapi.

Currently we have middleware that parses and validates the jwt token and adds the jwt.perms to req.perms, and the method would look something like

```route.get('/devices', acl(['device:read']), ...) { ... }```

**Comment by jsdevel** [comment]
If you want to do this the openapi way, you'd add `securityHandlers`.  Then you reference the security scheme in your method doc.

**Comment by memelet** [comment]
But how would the specific method required permissions be passed thru to the scheme?

**Comment by jsdevel** [comment]
please re-open here https://github.com/kogosoftwarellc/open-api
